-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 12:54:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidors` (
  `proveidor_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `adreça` VARCHAR(500) NOT NULL,
  `telefon` INT NOT NULL,
  `fax` INT NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proveidor_id`),
  UNIQUE INDEX `id_proveïdor_UNIQUE` (`proveidor_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `data_registre` DATETIME NOT NULL,
  `client_recomanacio` VARCHAR(45) NULL,
  `venedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `id_client_UNIQUE` (`client_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `ullera_id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio_vidre_dret` DECIMAL(5,2) NOT NULL,
  `graduacio_vidre_esquerra` DECIMAL(5,2) NOT NULL,
  `tipus_montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre_dret` VARCHAR(45) NOT NULL,
  `color_vidre_esquerra` VARCHAR(45) NOT NULL,
  `preu` DECIMAL(5,2) NOT NULL,
  `client_id` INT NOT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`ullera_id`),
  UNIQUE INDEX `id_ullera_UNIQUE` (`ullera_id` ASC) VISIBLE,
  INDEX `fk_Ulleres_Clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_Ulleres_Proveïdors1_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ulleres_Proveïdors1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `mydb`.`proveidors` (`proveidor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
